apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: rag3-jul29-1
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: rag3-jul29-1 
  name: rag3-jul29-1
spec:
  ports:
  - name: app
    port: 8501
    protocol: TCP
    targetPort: 8501
  - name: database
    port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app.kubernetes.io/instance: rag3-jul29-1 
